# Generated by Django 3.1.4 on 2021-01-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210107_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('id', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('area', models.CharField(max_length=12)),
                ('img', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='shopname',
            field=models.CharField(max_length=60),
        ),
    ]
