# Generated by Django 3.1.4 on 2021-01-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210107_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='fld',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
