# Generated by Django 3.1.4 on 2021-01-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_party_fld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='fld',
        ),
    ]
